# Generated by Django 5.0.6 on 2024-05-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='payment_method',
            field=models.CharField(choices=[(1, 'наличные'), (2, 'банковский перевод')], verbose_name='способ оплаты'),
        ),
    ]
