# Generated by Django 5.0.6 on 2024-05-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_pay_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='payment_method',
            field=models.CharField(choices=[('1', 'наличные'), ('2', 'банковский перевод')], verbose_name='способ оплаты'),
        ),
    ]
