# Generated by Django 5.0.6 on 2024-05-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pay_link_pay_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='payment_method',
            field=models.CharField(choices=[('1', 'наличные'), ('2', 'банковский перевод')], default=2, verbose_name='способ оплаты'),
        ),
    ]
